baseURL = "https://openbouffalo.github.io"
title = "open-bouffalo"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
# Enable 'Edit page' links
geekdocRepo = 'https://github.com/openbouffalo/openbouffalo.github.io'
geekdocEditPath = "edit/master"
